# Generated by Django 6.0.2 on 2026-03-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.FloatField(default=-12.483, help_text='Latitud para Google Maps'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.FloatField(default=-76.796, help_text='Longitud para Google Maps'),
        ),
    ]
